### ISSUE TITLE
Copy all content in textarea

### ISSUE THREAD

**Issue by arvindpdmn** [lyrasoft/ace-markdown-editor#31]
I want to know how to copy all text inside the editor's textarea. I find that the HTML textarea itself is empty. Text is captured in div tags line by line. However, not all lines are rendered. Only visible lines are rendered. I guess text must be stored/managed by editor's JS code somewhere. How can I copy the text?

Following is what I understand. Visible text can be accessed line by line:

                            <div class="ace_line_group">
                                <div class="ace_line" style="height:14.666671752929688px"><span class="ace_markup ace_list">*&nbsp;</span>[<span class="ace_string">His&nbsp;veniam&nbsp;partem&nbsp;alterum&nbsp;ei.&nbsp;Ei&nbsp;eros&nbsp;graeci&nbsp;usu,&nbsp;deleniti&nbsp;recusabo&nbsp;ut&nbsp;cum.</span>](<span class="ace_markup ace_underline">http://someurl</span></div>
                                <div class="ace_line" style="height:14.666671752929688px"><span class="ace_markup ace_underline">.com.in.uk</span>)</div>
                            </div>

**Comment by asika32764** [comment]
Do you want to copy text by Javascript?

Akmarkdown uses ACE editor, so you must read it's docs to know how to get editor content.
https://ace.c9.io/#nav=api

**Comment by arvindpdmn** [comment]
Could you guide me which class/method to use to copy the entire content? Meanwhile, I will look at the API.

**Comment by asika32764** [comment]
Maybe use `.getValue()`, I have years didn't touch this editor.

The ace instance is in `Akmarkdown.ace['xxx']`, `xxx` is id of your editor input, so if you want to get text from com_content, use `AKMarkdown.ace['jform_articletext'].getValue()`

**Comment by arvindpdmn** [comment]
Awesome! `AKMarkdown.ace['jform_articletext'].getValue()` works!

On a separate issue #30 , I said "I am unable to figure out the cursor position in the textarea and hence unable to paste the link as needed." Any help on this? Thx

**Comment by arvindpdmn** [comment]
I figure it out from the API reference:
`AKMarkdown.ace['jform_articletext'].insert("\nThis is a test.\n");`

API: Editor class: https://ace.c9.io/#nav=api&api=editor

**Comment by asika32764** [comment]
👍
